### ISSUE TITLE
[Apply] 111502558

### ISSUE THREAD

**Issue by FakeWood** [ncu-csie-student-association/nas-user-guide#2]
系級: 資工三B
學號: 111502558
姓名: 莊承儒
Email: jhuangchenleo@gmail.com

我同意遵循[使用規範](https://github.com/ncu-csie-student-association/nas-user-guide#%E4%BD%BF%E7%94%A8%E8%A6%8F%E7%AF%84)，且不上傳任何非法內容。

**Comment by an920107** [comment]
帳密已寄出，請檢查郵件信箱包括垃圾郵件
