### ISSUE TITLE
[Apply] 112502033

### ISSUE THREAD

**Issue by dianaanaana** [ncu-csie-student-association/nas-user-guide#3]
系級: 資工二B
學號: 112502033
姓名: 黃楷鈞
Email: noah940407@gmail.com

我同意遵循[使用規範](https://github.com/ncu-csie-student-association/nas-user-guide#%E4%BD%BF%E7%94%A8%E8%A6%8F%E7%AF%84)，且不上傳任何非法內容。

**Comment by an920107** [comment]
帳密已寄出，請檢查郵件信箱包括垃圾郵件
