### ISSUE TITLE
[Apply] 110502536

### ISSUE THREAD

**Issue by yuxin0214** [ncu-csie-student-association/nas-user-guide#5]
系級: 資工四B
學號: 110502536
姓名: 何妤馨
Email: 110502536@cc.ncu.edu.tw

我同意遵循[使用規範](https://github.com/ncu-csie-student-association/nas-user-guide#%E4%BD%BF%E7%94%A8%E8%A6%8F%E7%AF%84)，且不上傳任何非法內容。

**Comment by an920107** [comment]
帳密已寄出，請檢查郵件信箱包括垃圾郵件
